server:
  port: 8090
jwt:
  secret: ${JWT_SECRET:secret123}
  expiresSeconds: ${JWT_EXPIRES_SECONDS:7200}
users:
  service:
    url: ${USERS_SERVICE_URL:http://users-service:8081}
management:
  endpoints:
    web:
      exposure:
        include: "*"
